use_frameworks!

platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'
target 'UniversalBarKit_Example' do
  pod 'UniversalBarKit', :path => '../'
  pod 'lottie-ios','~> 2.5.3',:modular_headers => true
  target 'UniversalBarKit_Tests' do
    inherit! :search_paths

    
  end
end
